// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYeuUpEgxPbUo2O6QB2GmVnifNs6UQ9E',
    appId: '1:147117910130:web:50f9c9cc637614f714faeb',
    messagingSenderId: '147117910130',
    projectId: 'notesnap-2a9f1',
    authDomain: 'notesnap-2a9f1.firebaseapp.com',
    storageBucket: 'notesnap-2a9f1.appspot.com',
    measurementId: 'G-2NX4RWVXG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE7draosc2uOFrUvqv4bF4tnTqMN-Zu_g',
    appId: '1:147117910130:android:83f8246f35549e1714faeb',
    messagingSenderId: '147117910130',
    projectId: 'notesnap-2a9f1',
    storageBucket: 'notesnap-2a9f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW5WlfUAN2ywh663n87pe__7loEHmREcg',
    appId: '1:147117910130:ios:4c4f94943d187a5214faeb',
    messagingSenderId: '147117910130',
    projectId: 'notesnap-2a9f1',
    storageBucket: 'notesnap-2a9f1.appspot.com',
    iosClientId:
        '147117910130-fjt66b1jngmv3kgtrj1tpsi7iv301gup.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepad',
  );
}
